### ISSUE TITLE
Failed to build package

### ISSUE THREAD

**Issue by karanchawla** [husky/husky_simulator#30]
```Errors     << husky_description:cmake /home/karan/ETHZ ROS Course/Week 1/catkin_ws/logs/husky_description/build.cmake.000.log

/home/karan/ETHZ ROS Course/Week 1/catkin_ws/devel/.private/husky_description/env.sh: 1: export: Course/Week: bad variable name
Traceback (most recent call last):
  File "/home/karan/ETHZ ROS Course/Week 1/catkin_ws/build/husky_description/catkin_generated/generate_cached_setup.py", line 22, in <module>

    code = generate_environment_script('/home/karan/ETHZ ROS Course/Week 1/catkin_ws/devel/.private/husky_description/env.sh')

  File "/opt/ros/kinetic/lib/python2.7/dist-packages/catkin/environment_cache.py", line 61, in generate_environment_script
    output = subprocess.check_output([env_script, sys.executable, '-c', python_code])

  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)

subprocess.CalledProcessError: Command '['/home/karan/ETHZ ROS Course/Week 1/catkin_ws/devel/.private/husky_description/env.sh', '/usr/bin/python', '-c', 'import os; print(dict(os.environ))']' returned non-zero exit status 2

CMake Error at /opt/ros/kinetic/share/catkin/cmake/safe_execute_process.cmake:11 (message):
  execute_process(/usr/bin/python "/home/karan/ETHZ ROS Course/Week
  1/catkin_ws/build/husky_description/catkin_generated/generate_cached_setup.py")
  returned error code 1

Call Stack (most recent call first):
  /opt/ros/kinetic/share/catkin/cmake/catkin_add_env_hooks.cmake:138 (safe_execute_process)
  CMakeLists.txt:7 (catkin_add_env_hooks)
```

Trying to build this on Ubuntu 16.04 running ROS Kinetic. Is there something I'm missing?

**Comment by paulbovbel** [comment]
All husky bits have been moved to a monorepo for kinetic development, see https://github.com/husky/husky/tree/kinetic-devel
