### ISSUE TITLE
view_robot.launch crashes on hydro (ubuntu 12.04.4)

### ISSUE THREAD

**Issue by kjeremy** [husky/husky_simulator#5]
`roslaunch husky_viz view_robot.launch`

```
setting /run_id to 55abae76-935c-11e3-aaa4-000c290ae390
process[rosout-1]: started with pid [54530]
started core service [/rosout]
process[interactive_markers-2]: started with pid [54542]
process[joint_state_publisher-3]: started with pid [54560]
process[rviz-4]: started with pid [54561]
Traceback (most recent call last):
  File "/opt/ros/hydro/lib/joint_state_publisher/joint_state_publisher", line 327, in <module>
    jsp = JointStatePublisher()
  File "/opt/ros/hydro/lib/joint_state_publisher/joint_state_publisher", line 25, in __init__
    robot = xml.dom.minidom.parseString(description).getElementsByTagName('robot')[0]
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1930, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
TypeError: must be string or read-only buffer, not None
```

**Comment by mikepurvis** [comment]
Hi Jeremy— the `view_robot.launch` launcher is designed to be used with a separately-launched robot or simulator. It looks like there was no robot description found, hence the crash in rviz.

If you only want to view the robot model in isolation, try `view_model.launch`.

**Comment by kjeremy** [comment]
Thanks.  view_model.launch is resulting in a white model.

The RobotModel shows a Status:Error with:
`back_left_wheel: No transform from [back_left_wheel] to [odom]`

I also see a Global Status: Error, Fixed Frame[odom] does not exist.

**Comment by mikepurvis** [comment]
Try setting the rviz frame to `base_link` from `odom`.
